### PR TITLE
Update get-pkg/reflinks

### PR DESCRIPTION
**Pull request by stefanwalther**

### CODE REVIEW

**Comment by stefanwalther** [comment]
@jonschlinkert Ready to be merged, IMHO.
Please also do a `npm publish`.

Thx a lot.

**Comment by jonschlinkert** [comment]
I know we asked you to update the engine on a prior pr, but it would probably be faster if you just update the dependency only. 

All I have to do is run `update` and all files in the project are updated to the latest conventions.

**Comment by stefanwalther** [comment]
All fine, not an issue to me.

**Comment by jonschlinkert** [comment]
sorry I had time to get this done and assumed it was more important to you to have the fix than for me to wait.

**Comment by stefanwalther** [comment]
Thx

**Pull request merged**
